# Generated by Django 6.0.2 on 2026-02-25 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0002_classsession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
    ]
