# Generated by Django 4.2.28 on 2026-02-25 15:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0004_alter_assignment_due_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studyplan',
            old_name='plan_hours',
            new_name='plan_days',
        ),
        migrations.RemoveField(
            model_name='studyplan',
            name='plan_date',
        ),
        migrations.AddField(
            model_name='studyplan',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
