# Generated by Django 4.2.28 on 2026-02-25 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0005_rename_plan_hours_studyplan_plan_days_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='assignment',
            constraint=models.UniqueConstraint(fields=('course', 'title'), name='uniq_assignment_title_per_course'),
        ),
    ]
