# Generated by Django 4.2.29 on 2026-03-05 22:07

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0006_assignment_uniq_assignment_title_per_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studyplan',
            name='plan_days',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
    ]
