# Generated by Django 4.2.29 on 2026-03-06 00:05

from django.db import migrations, models
import datetime


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0007_alter_studyplan_plan_days'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studyplan',
            name='plan_days',
        ),
        migrations.AddField(
            model_name='studyplan',
            name='plan_duration',
            field=models.DurationField(default=datetime.timedelta(seconds=0)),
            preserve_default=False,
        ),
    ]
